<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>JoLe</title>
    <link href="/css/style.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="js/jquery-1.8.2.min.js"></script>
</head>
    
<body>
    
    <div id="header">

	<div id="logo"> <img src="/images/brainwork_logo.jpg" /> </div>
	
        <?php $auth = Zend_Auth::getInstance();
        if ( $auth->hasIdentity()) : ?>

                <div id="menu">
                        <ul>
                                <li><a href="obras/listar">Obras</a></li>
                                <li><a href="#">Clientes</a></li>
                                <li><a href="#">Pagos</a></li>
                                <li><a href="#">Usuarios</a></li>
                        </ul>
                </div>

        <div id="session"> Ha iniciado sesion como: <?php echo $auth->getIdentity() ?> <a href="/usuarios/logout" style="text-decoration: none; color:red;">[Logout]</a> </div>
        
        <?php endif; ?>
	
    </div>

    <div id="cuerpoPrincipal">

            <?php echo $this->layout()->content; ?>

    </div>
    
</body>
        

</html>